# Generated by Django 6.0.5 on 2026-06-18 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_achievement_profile_achievements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Achievement',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
