# Generated by Django 6.0.5 on 2026-06-13 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('swaps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('swap_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='swaps.swaprequest')),
            ],
        ),
    ]
