# Generated by Django 6.0.5 on 2026-06-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_skill_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('Programming', 'Programming'), ('Math', 'Math'), ('Science', 'Science'), ('Language', 'Language'), ('Business', 'Business'), ('Design', 'Design')], default='Programming', max_length=50),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
